[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
kinode_process_lib = { git = "https://github.com/kinode-dao/process_lib", tag = "v0.7.0" }
wit-bindgen = "0.24.0"



[lib]
crate-type = ["cdylib"]


[package.metadata.component]
package = "kinode:process"
